apiVersion: v1
kind: Secret
metadata:
  name: {{ app.name }}
type: Opaque
{%- if app.secret is not none %}
data:
{%- for key, value in app.secret.iteritems() %}
  {{ key }}: {{ value }}
{%- endfor %}
{%-endif %}
